name: Check Links

on:
  schedule:
    # Run weekly on Sundays at 00:00 UTC
    - cron: '0 0 * * 0'
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

# Give the GITHUB_TOKEN permission to create issues
permissions:
  contents: read
  issues: write

jobs:
  linkChecker:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    
    - name: Link Checker
      uses: lycheeverse/lychee-action@v1.10.0
      with:
        args: --verbose --no-progress './README.md'
        fail: true
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    
    - name: Create Issue From File
      if: failure()
      uses: peter-evans/create-issue-from-file@v5
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
        title: "Broken Links Detected"
        content-filepath: ./lychee/out.md
        labels: |
          bug
          automated issue